name: xayn_readability_core
description: Core readability package
version: 0.0.1
publish_to: none
homepage: https://www.xayn.com

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  html: ^0.15.0
  http_client: ^1.5.1

dev_dependencies:
  lints: ^2.0.0
  test: any
